cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED SOURCE_DIR OR SOURCE_DIR STREQUAL "")
  message(FATAL_ERROR "SOURCE_DIR is required.")
endif()

set(_artifacts
  "data/random/new-joe-kuo-6.21201|68eedd2a4e3b659b9695e7aff0f8ac68718bcf620730fc3d3a8c65df2a067441"
  "data/random/LICENSE.joe-kuo|9d10226b50eeb34be0ab06bfa3392c7bd1f04bf602f9af4343295d1fd003d0e3"
  "tools/random/generate_sobol_table.py|613a25efbd18ef1226af5539c934631279f3d37ddf79ad4d51f33f69886137d0"
  "src/random/sobol_table_generated.cc|014a253a00b5493dde3ceeaef48aebf4a765e8db0b562940b7e931972f69784f"
  "THIRD_PARTY_NOTICES|ccf7c082d57890a198916874bc4606e7e8a04621781a45c0e185af3c03c0cff1"
)
foreach(_record IN LISTS _artifacts)
  string(REPLACE "|" ";" _fields "${_record}")
  list(GET _fields 0 _relative_path)
  list(GET _fields 1 _expected_sha256)
  set(_path "${SOURCE_DIR}/${_relative_path}")
  if(NOT EXISTS "${_path}")
    message(FATAL_ERROR "Required Sobol artifact is absent: ${_relative_path}")
  endif()
  file(SHA256 "${_path}" _observed_sha256)
  if(NOT _observed_sha256 STREQUAL _expected_sha256)
    message(FATAL_ERROR
      "Sobol artifact ${_relative_path} has SHA-256 ${_observed_sha256}; "
      "expected ${_expected_sha256}."
    )
  endif()
endforeach()

file(READ "${SOURCE_DIR}/src/random/sobol_table_generated.cc" _generated)
foreach(_required_text IN ITEMS
    "Generated by tools/random/generate_sobol_table.py. Do not edit."
    "Source SHA-256: 68eedd2a4e3b659b9695e7aff0f8ac68718bcf620730fc3d3a8c65df2a067441"
    "return 0x3BB4490E95B9B169ULL"
)
  string(FIND "${_generated}" "${_required_text}" _position)
  if(_position EQUAL -1)
    message(FATAL_ERROR "Generated Sobol table omits: ${_required_text}")
  endif()
endforeach()

message(STATUS "Pinned Sobol data, license, generator, output, and notice validate.")
