#include <algorithm>
#include <array>
#include <complex>
#include <cstddef>
#include <filesystem>
#include <iostream>
#include <span>
#include <string_view>

#include "asc/core/array_format.h"
#include "asc/core/array_io.h"
#include "asc/core/extents.h"
#include "asc/core/io.h"
#include "asc/core/matrix_market.h"
#include "asc/core/memory.h"
#include "asc/core/result.h"
#include "asc/core/status.h"
#include "asc/core/types.h"
#include "asc/dense/array.h"
#include "asc/dense/layout.h"
#include "asc/dense/matrix_market.h"
#include "asc/dense/print.h"
#include "asc/dense/view.h"

namespace {
using Value = std::complex<double>;
using Shape = asc::Extents<asc::kDynamicExtent, asc::kDynamicExtent>;
using Matrix = asc::DenseArray<Value, Shape>;

// Hand-derived lower-triangle column order, not output generated by ASC.
constexpr std::string_view kInput =
    "%%MatrixMarket matrix array complex hermitian\n"
    "% Rows are (4, 2-2i), (2+2i, 11).\n"
    "2 2\n4 0\n2 2\n11 0\n";
constexpr std::string_view kTruncated =
    "%%MatrixMarket matrix array complex hermitian\n2 2\n4 0\n2 2\n";

class LiteralSource final : public asc::ByteSource {
 public:
  explicit LiteralSource(std::string_view input) : remaining_(input) {}
  asc::Result<std::size_t> ReadSome(std::span<std::byte> output) override {
    const auto count = std::min(output.size(), remaining_.size());
    for (std::size_t i = 0; i < count; ++i) {
      output[i] = static_cast<std::byte>(remaining_[i]);
    }
    remaining_.remove_prefix(count);
    return count;
  }

 private:
  std::string_view remaining_;
};

class StandardOutput final : public asc::ByteSink {
 public:
  asc::Result<std::size_t> WriteSome(
      std::span<const std::byte> input) override {
    std::cout.write(reinterpret_cast<const char*>(input.data()),
                    static_cast<std::streamsize>(input.size()));
    return std::cout ? asc::Result<std::size_t>(input.size())
                     : asc::Status(asc::ErrorCode::kIo);
  }
};

asc::Status CheckValues(const Matrix& matrix) {
  const auto view = matrix.view();
  if (!view.ok()) {
    return view.status();
  }
  constexpr std::array<Value, 4> kExpected{Value{4, 0}, Value{2, -2},
                                           Value{2, 2}, Value{11, 0}};
  for (std::size_t row = 0; row < 2; ++row) {
    for (std::size_t column = 0; column < 2; ++column) {
      if (view->data()[row * view->strides()[0] +
                       column * view->strides()[1]] !=
          kExpected[2 * row + column]) {
        return asc::Status(asc::ErrorCode::kInternal);
      }
    }
  }
  return asc::Status::Ok();
}

asc::Status CheckRollback(Matrix& matrix) {
  auto view = matrix.view();
  if (!view.ok()) {
    return view.status();
  }
  std::array<Value, 4> before{};
  std::copy_n(view->data(), before.size(), before.data());
  std::array<Value, 4> staging{};
  std::array<std::byte, 512> scratch{};
  asc::ArrayIoReport report;
  LiteralSource truncated(kTruncated);
  auto reader =
      asc::DenseMatrixMarketReader::Prepare(truncated, scratch, {}, report);
  if (!reader.ok()) {
    return reader.status();
  }
  const auto status =
      asc::ReadDenseMatrixMarketInto(*reader, *view, std::span(staging));
  if (status.ok() || report.committed ||
      !std::equal(before.begin(), before.end(), view->data())) {
    return asc::Status(asc::ErrorCode::kInternal);
  }
  return asc::Status::Ok();
}

asc::Status Run(const std::filesystem::path& directory) {
  asc::HostMemoryResource resource;
  const asc::ArrayIoLimits limits;
  std::array<std::byte, 512> scratch{};
  asc::ArrayIoReport report;
  LiteralSource source(kInput);
  auto original = asc::ReadDenseMatrixMarket<Value, Shape>(
      source, resource, asc::LayoutRight{}, scratch, limits, report);
  if (!original.ok()) {
    return original.status();
  }
  auto status = CheckValues(*original);
  if (!status.ok()) {
    return status;
  }
  auto view = original->view();
  if (!view.ok()) {
    return view.status();
  }
  const auto path = directory / "dense-hermitian.mtx";
  status = asc::SaveDenseMatrixMarket(
      path, *view, asc::MatrixMarketSymmetry::kHermitian,
      asc::ArrayFileOverwrite::kTruncate, limits, scratch, report);
  if (!status.ok()) {
    return status;
  }
  auto reloaded = asc::LoadDenseMatrixMarket<Value, Shape>(
      path, resource, asc::LayoutLeft{}, scratch, limits, report);
  if (!reloaded.ok()) {
    return reloaded.status();
  }
  status = CheckValues(*reloaded);
  if (status.ok()) {
    status = CheckRollback(*reloaded);
  }
  if (!status.ok()) {
    return status;
  }
  StandardOutput output;
  asc::ArrayPrintOptions options;
  options.max_elements = 4;
  asc::ArrayPrintReport printing;
  status = asc::PrintArray(*reloaded, output, options, scratch, printing);
  if (status.ok()) {
    std::cout << "\nHermitian array interchange, layout conversion and "
                 "malformed-input rollback verified.\n";
  }
  return status;
}
}  // namespace

int main(int argc, char** argv) {
  if (argc != 3 || std::string_view(argv[1]) != "--truncate") {
    std::cerr << "Usage: dense_matrix_market --truncate EXISTING_OUTPUT_DIR\n";
    return 2;
  }
  const auto status = Run(std::filesystem::path(argv[2]));
  if (!status.ok()) {
    std::cerr << "Matrix Market example failed: "
              << static_cast<int>(status.code()) << '\n';
    return 1;
  }
  return 0;
}
