cmake_minimum_required(VERSION 3.25)
project(ASCCppMatrixScaleExample LANGUAGES CXX)
find_package(ASCCpp 0.9 CONFIG REQUIRED COMPONENTS dense_lapack)
add_executable(matrix_scale main.cc)
target_compile_features(matrix_scale PRIVATE cxx_std_20)
target_link_libraries(matrix_scale PRIVATE ASC::dense_lapack)
enable_testing()
add_test(NAME matrix_scale.public_example COMMAND matrix_scale)
