# Linux ELF package checks for the explicitly selected shared provider profile.
# No provider/runtime file is copied, loaded or executed by this inspection.
function(asc_cpp_check_shared_lapack_runtime executable provider_root metadata log)
  set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM linux+elf)
  set(CMAKE_GET_RUNTIME_DEPENDENCIES_TOOL objdump)
  file(GET_RUNTIME_DEPENDENCIES EXECUTABLES "${executable}"
    RESOLVED_DEPENDENCIES_VAR _resolved UNRESOLVED_DEPENDENCIES_VAR _unresolved
    CONFLICTING_DEPENDENCIES_PREFIX _conflicts)
  if(_unresolved OR _conflicts_FILENAMES)
    message(FATAL_ERROR "Unresolved or conflicting installed runtime dependencies: ${executable}")
  endif()
  set(_actual)
  foreach(_dependency IN LISTS _resolved)
    file(REAL_PATH "${_dependency}" _real)
    list(APPEND _actual "${_real}")
  endforeach()
  set(_provider_files)
  foreach(_index RANGE 0 2)
    string(JSON _path GET "${metadata}" libraries ${_index} path)
    string(JSON _expected GET "${metadata}" libraries ${_index} sha256)
    file(REAL_PATH "${provider_root}/${_path}" _library)
    if(NOT _library IN_LIST _actual)
      message(FATAL_ERROR "Installed consumer did not resolve its attested provider: ${_path}")
    endif()
    file(SHA256 "${_library}" _observed)
    if(NOT _observed STREQUAL _expected)
      message(FATAL_ERROR "Installed provider runtime hash mismatch: ${_path}")
    endif()
    list(APPEND _provider_files "${_library}")
  endforeach()
  foreach(_index RANGE 0 1)
    string(JSON _name GET "${metadata}" runtimes ${_index} name)
    string(JSON _expected GET "${metadata}" runtimes ${_index} sha256)
    set(_found FALSE)
    foreach(_library IN LISTS _actual)
      cmake_path(GET _library FILENAME _filename)
      if(_filename STREQUAL _name)
        file(SHA256 "${_library}" _observed)
        if(NOT _observed STREQUAL _expected)
          message(FATAL_ERROR "Installed foreign runtime hash mismatch: ${_name}")
        endif()
        set(_found TRUE)
      endif()
    endforeach()
    if(NOT _found)
      message(FATAL_ERROR "Installed consumer omitted its attested runtime: ${_name}")
    endif()
  endforeach()
  foreach(_library IN LISTS _actual)
    cmake_path(GET _library FILENAME _filename)
    if(_filename MATCHES "^lib(lapacke?|blas|openblas).*\\.so"
       AND NOT _library IN_LIST _provider_files)
      message(FATAL_ERROR "Installed consumer resolved an alternate provider: ${_library}")
    endif()
  endforeach()
  file(APPEND "${log}" "${executable}\n${_actual}\n")
endfunction()

function(asc_cpp_check_provider_free_runtime library log)
  set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM linux+elf)
  set(CMAKE_GET_RUNTIME_DEPENDENCIES_TOOL objdump)
  file(GET_RUNTIME_DEPENDENCIES LIBRARIES "${library}"
    RESOLVED_DEPENDENCIES_VAR _resolved UNRESOLVED_DEPENDENCIES_VAR _unresolved
    CONFLICTING_DEPENDENCIES_PREFIX _conflicts)
  if(_unresolved OR _conflicts_FILENAMES)
    message(FATAL_ERROR "Unresolved or conflicting base runtime dependencies: ${library}")
  endif()
  foreach(_dependency IN LISTS _resolved)
    cmake_path(GET _dependency FILENAME _filename)
    if(_filename MATCHES "^lib(lapacke?|blas|openblas|gfortran|quadmath).*\\.so")
      message(FATAL_ERROR "Provider-free ASC library acquired a foreign dependency: ${library}")
    endif()
  endforeach()
  file(APPEND "${log}" "${library}\n${_resolved}\n")
endfunction()
