cmake_minimum_required(VERSION 3.25)
project(ASCCppGeneralLuExample LANGUAGES CXX)
find_package(ASCCpp 0.9 CONFIG REQUIRED COMPONENTS dense_lapack)
find_package(Threads REQUIRED)
add_executable(general_lu main.cc)
target_compile_features(general_lu PRIVATE cxx_std_20)
target_link_libraries(general_lu PRIVATE ASC::dense_lapack Threads::Threads)
enable_testing()
add_test(NAME general_lu.public_modes COMMAND general_lu)
