"""Generate exact dyadic rounding fixtures without ASC or a decimal parser.

Each binary bit pattern defines an exact Fraction. Its midpoint with the next
pattern has a terminating decimal expansion, computed entirely with integers.
Expected ties are resolved by the low bit of the supplied binary significand.
"""

import argparse
import fractions
import pathlib


def value(bits, fraction_bits, bias):
    """Return the dyadic value, allowing the virtual overflow endpoint."""
    exponent = bits >> fraction_bits
    fraction = bits & ((1 << fraction_bits) - 1)
    significand = fraction if exponent == 0 else (1 << fraction_bits) + fraction
    power = (1 - bias if exponent == 0 else exponent - bias) - fraction_bits
    return fractions.Fraction(significand) * fractions.Fraction(2) ** power


def decimal(number):
    """Spell a dyadic rational exactly using its power-of-two denominator."""
    power = number.denominator.bit_length() - 1
    assert number.denominator == 1 << power
    digits = str(number.numerator * 5**power)
    if power == 0:
        return digits
    digits = digits.zfill(power + 1)
    return digits[:-power] + "." + digits[-power:]


def generate():
    """Return a private test header with independently specified bit answers."""
    lines = [
        "// Generated by tools/array_io/generate_decimal_fixtures.py.",
        "// Exact Fraction midpoints; no ASC writer/parser or floating arithmetic.",
        "#ifndef ASC_TESTS_CORE_ARRAY_PARSE_CASES_H_",
        "#define ASC_TESTS_CORE_ARRAY_PARSE_CASES_H_",
        "",
        "#include <cstdint>",
        "#include <string_view>",
        "",
        "namespace asc_core_test {",
        "struct DecimalCase {",
        "  std::string_view token;",
        "  std::uint64_t bits;",
        "  bool overflow;",
        "};",
    ]
    for name, fraction, bias, maximum in [
        ("Float", 23, 127, 0x7F7FFFFF),
        ("Double", 52, 1023, 0x7FEFFFFFFFFFFFFF),
    ]:
        minimum_normal = 1 << fraction
        one = bias << fraction
        patterns = [0, 1, 2, minimum_normal - 2, minimum_normal - 1,
                    minimum_normal, one - 2, one - 1, one, one + 1,
                    maximum - 2, maximum - 1, maximum]
        lines.append(f"inline constexpr DecimalCase k{name}DecimalCases[] = {{")
        for bits in patterns:
            lower = value(bits, fraction, bias)
            upper = value(bits + 1, fraction, bias)
            midpoint = (lower + upper) / 2
            for number, expected in [
                ((lower + midpoint) / 2, bits),
                (midpoint, bits + (bits & 1)),
                ((midpoint + upper) / 2, bits + 1),
            ]:
                token = decimal(number)
                lines.append("    {")
                lines.extend(f'        "{token[i:i + 64]}"'
                             for i in range(0, len(token), 64))
                overflow = expected == 0 or expected > maximum
                lines.append(f"        , 0x{expected:x}ULL, "
                             + ("true" if overflow else "false") + "},")
        lines.append("};")
    lines.extend(["}  // namespace asc_core_test", "", "#endif", ""])
    return "\n".join(lines)


def main():
    """Write the fixture header; callers apply repository clang-format."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()
    args.output.write_text(generate(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
