cmake_minimum_required(VERSION 3.25)
project(ASCCppDmdQrExample LANGUAGES CXX)
find_package(ASCCpp 0.9 CONFIG REQUIRED COMPONENTS dense_lapack)
add_executable(dmd_qr main.cc)
target_compile_features(dmd_qr PRIVATE cxx_std_20)
target_link_libraries(dmd_qr PRIVATE ASC::dense_lapack)
enable_testing()
add_test(NAME dmd_qr.public_example COMMAND dmd_qr)
