# Private dependency loader, used only for an explicitly requested Dense facet.
# No system BLAS/LAPACK search and no C/Fortran language enablement occur here.
include_guard(GLOBAL)

function(asc_internal_lapack_dependencies
    metadata prefix runtime_libraries error_variable expected_identity
    expected_metadata_sha256)
  set("${error_variable}" "" PARENT_SCOPE)
  if(NOT EXISTS "${metadata}" OR IS_DIRECTORY "${metadata}")
    set("${error_variable}" "Reference provider metadata is missing." PARENT_SCOPE)
    return()
  endif()
  # The generated ASC config is trusted. Binding its exact metadata digest
  # catches stale/mixed records, not an attacker who changes both files.
  file(SHA256 "${metadata}" _metadata_sha256)
  if(NOT _metadata_sha256 STREQUAL expected_metadata_sha256)
    set("${error_variable}" "Reference provider metadata digest mismatch." PARENT_SCOPE)
    return()
  endif()
  if(NOT IS_DIRECTORY "${prefix}")
    set("${error_variable}" "An explicit ASC_CPP_LAPACK_ROOT is required." PARENT_SCOPE)
    return()
  endif()
  file(REAL_PATH "${prefix}" _prefix)
  file(READ "${metadata}" _metadata)
  string(JSON _schema ERROR_VARIABLE _schema_error GET "${_metadata}" schema_version)
  string(JSON _bits ERROR_VARIABLE _bits_error GET "${_metadata}" integer_bits)
  string(JSON _profile ERROR_VARIABLE _profile_error GET "${_metadata}" profile)
  if(_schema_error OR NOT _schema STREQUAL "1"
     OR _bits_error OR NOT _bits MATCHES "^(32|64)$"
     OR _profile_error OR NOT _profile STREQUAL "incremental-factorizations-v6")
    set("${error_variable}" "Unsupported reference provider schema, ABI or capability profile." PARENT_SCOPE)
    return()
  endif()
  string(JSON _identity ERROR_VARIABLE _json_error GET "${_metadata}" identity_sha256)
  if(_json_error)
    set("${error_variable}" "Malformed reference identity metadata." PARENT_SCOPE)
    return()
  endif()
  string(LENGTH "${_identity}" _identity_length)
  if(NOT _identity_length EQUAL 64 OR NOT _identity MATCHES "^[0-9a-f]+$"
     OR NOT _identity STREQUAL expected_identity)
    set("${error_variable}" "Reference identity differs from the compiled ASC facet." PARENT_SCOPE)
    return()
  endif()
  string(JSON _library_count ERROR_VARIABLE _json_error LENGTH "${_metadata}" libraries)
  if(_json_error)
    set("${error_variable}" "Malformed reference library metadata." PARENT_SCOPE)
    return()
  endif()
  if(NOT _library_count EQUAL 3)
    set("${error_variable}" "The reference dependency needs LAPACKE, LAPACK and BLAS." PARENT_SCOPE)
    return()
  endif()
  set(_links)
  set(_stems lapacke lapack blas)
  set(_suffix)
  if(_bits STREQUAL "64")
    set(_suffix "64")
  endif()
  foreach(_index RANGE 0 2)
    string(JSON _relative ERROR_VARIABLE _path_error GET "${_metadata}" libraries ${_index} path)
    string(JSON _expected ERROR_VARIABLE _hash_error GET "${_metadata}" libraries ${_index} sha256)
    if(_path_error OR _hash_error OR _relative STREQUAL "")
      set("${error_variable}" "Malformed reference library record." PARENT_SCOPE)
      return()
    endif()
    list(GET _stems ${_index} _stem)
    if(NOT _relative MATCHES "(^|/)lib${_stem}${_suffix}\\.a$")
      set("${error_variable}" "Unexpected reference library role or integer ABI." PARENT_SCOPE)
      return()
    endif()
    cmake_path(IS_ABSOLUTE _relative _absolute)
    if(_absolute OR _relative MATCHES "(^|/)\\.\\.(/|$)")
      set("${error_variable}" "Provider metadata contains an escaping library path." PARENT_SCOPE)
      return()
    endif()
    file(REAL_PATH "${_prefix}/${_relative}" _library)
    cmake_path(IS_PREFIX _prefix "${_library}" NORMALIZE _inside)
    if(NOT _inside OR NOT EXISTS "${_library}")
      set("${error_variable}" "Provider library is missing or escapes its prefix." PARENT_SCOPE)
      return()
    endif()
    file(SHA256 "${_library}" _observed)
    if(NOT _observed STREQUAL _expected)
      set("${error_variable}" "Provider library hash mismatch: ${_relative}" PARENT_SCOPE)
      return()
    endif()
    list(APPEND _links "${_library}")
  endforeach()

  # Runtime libraries are explicit inputs. Their exact binary identities are
  # frozen by the ASC provider build; never let a bare -lgfortran find a rival.
  string(JSON _runtime_count ERROR_VARIABLE _json_error LENGTH "${_metadata}" runtimes)
  if(_json_error)
    set("${error_variable}" "Malformed reference runtime metadata." PARENT_SCOPE)
    return()
  endif()
  if(NOT _runtime_count EQUAL 2)
    set("${error_variable}" "The reference provider requires exactly two audited runtimes." PARENT_SCOPE)
    return()
  endif()
  math(EXPR _last_runtime "${_runtime_count} - 1")
  set(_runtime_kinds)
  foreach(_index RANGE 0 ${_last_runtime})
    string(JSON _name ERROR_VARIABLE _name_error GET "${_metadata}" runtimes ${_index} name)
    string(JSON _expected ERROR_VARIABLE _hash_error GET "${_metadata}" runtimes ${_index} sha256)
    if(_name_error OR _hash_error)
      set("${error_variable}" "Malformed reference runtime record." PARENT_SCOPE)
      return()
    endif()
    if(NOT _name MATCHES "^lib(gfortran|quadmath)\\.so\\.[0-9.]+$")
      set("${error_variable}" "Unexpected reference runtime role." PARENT_SCOPE)
      return()
    endif()
    list(APPEND _runtime_kinds "${CMAKE_MATCH_1}")
    set(_match)
    foreach(_candidate IN LISTS runtime_libraries)
      if(IS_ABSOLUTE "${_candidate}" AND EXISTS "${_candidate}")
        file(REAL_PATH "${_candidate}" _resolved)
        cmake_path(GET _resolved FILENAME _candidate_name)
        if(_candidate_name STREQUAL _name)
          file(SHA256 "${_resolved}" _observed)
          if(NOT _observed STREQUAL _expected)
            set("${error_variable}" "Reference runtime hash mismatch: ${_name}" PARENT_SCOPE)
            return()
          endif()
          set(_match "${_resolved}")
        endif()
      endif()
    endforeach()
    if(NOT _match)
      set("${error_variable}" "Explicit ASC_CPP_LAPACK_RUNTIME_LIBRARIES omits attested runtime ${_name}." PARENT_SCOPE)
      return()
    endif()
    list(APPEND _links "${_match}")
  endforeach()
  list(SORT _runtime_kinds)
  if(NOT _runtime_kinds STREQUAL "gfortran;quadmath")
    set("${error_variable}" "Duplicate or missing reference runtime role." PARENT_SCOPE)
    return()
  endif()
  if(TARGET ASC_INTERNAL_LAPACK::reference)
    get_target_property(_existing ASC_INTERNAL_LAPACK::reference ASC_LAPACK_IDENTITY)
    get_target_property(_existing_links ASC_INTERNAL_LAPACK::reference INTERFACE_LINK_LIBRARIES)
    if(NOT _existing STREQUAL _identity OR NOT _existing_links STREQUAL _links)
      set("${error_variable}" "A different reference provider was already selected." PARENT_SCOPE)
      return()
    endif()
    return()
  endif()
  add_library(ASC_INTERNAL_LAPACK::reference INTERFACE IMPORTED GLOBAL)
  set_target_properties(ASC_INTERNAL_LAPACK::reference PROPERTIES
    ASC_LAPACK_IDENTITY "${_identity}"
    INTERFACE_LINK_LIBRARIES "${_links}"
  )
endfunction()
